'use client'
import React, { useState } from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBandcamp } from '@fortawesome/free-brands-svg-icons'
import { faArrowDown, faRotateLeft, faStar } from '@fortawesome/free-solid-svg-icons'
import { Inter } from 'next/font/google'
import { useTheme } from '../useTheme'
import { Bungee } from 'next/font/google'
import { Changa_One } from 'next/font/google'
import {useRouter} from 'next/navigation'
import { useEffect }  from 'react'
import Profilepage from './profilepage/page'
import History from './history/page'
import Settings from './setting/page'
import KarinaChat from './karinachat/page'




const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic']
})
const bungee = Bungee({
  subsets: ['latin'],
  weight: '400'
})

const changa = Changa_One({
  subsets: ['latin'],
  weight: ['400',],
  style: ['normal', 'italic']
})

// find these 4 constants and replace all of them

// ── REPLACE ALL 4 CONSTANTS ──
const getBox = (isDark) => 
`w-[95%] sm:w-[92%] md:w-[90%] flex-col flex justify-center items-center 
gap-2 sm:gap-7 md:gap-8 lg:gap-9 xl:gap-5
flex-shrink-0 transition-all duration-300 
min-h-[320px] sm:min-h-[360px] md:min-h-[400px] lg:min-h-[460px] xl:min-h-[550px]
border-t-3 sm:border-t-4 md:border-t-6 lg:border-t-8 xl:border-t-10
rounded-[14px] sm:rounded-[16px] md:rounded-[20px]
shadow-md shadow-[#6367FF]/80
${isDark ? 'border-[#C9BEFF]/80' : 'border-[#6367FF]/80'}
${isDark ? 'bg-[#000000]' : 'bg-white'}`

const getBoxtext = (isDark) => `min-h-[24px] sm:min-h-[28px] md:min-h-[32px] lg:min-h-[36px] xl:min-h-[40px] 
w-[98%] sm:w-[90%] md:w-[82%] lg:w-[72%] xl:w-[95%] 
text-[10px] sm:text-[11px] md:text-[13px] lg:text-[16px] xl:text-[17px] 
rounded-[8px] sm:rounded-[12px] md:rounded-[16px] lg:rounded-[20px] 
flex justify-start items-center flex-wrap 
 px-2 sm:px-3 md:px-4 py-[3px] sm:py-1 
mt-[3px] sm:mt-1 md:mt-2 font-bold italic 
${isDark ? 'text-white/80' : 'text-[#471396]'}
 ${isDark ? ' bg-[#C9BEFF]/50 border-[#C9BEFF]/20 shadow-md shadow-[#6367FF]/80' : 'bg-[#6367FF]/20 border border-[#6367FF]/20 shadow-md shadow-[#000000]/40'}`

const getBoxtext2 = (isDark) => `min-h-[24px] sm:min-h-[28px] md:min-h-[32px] lg:min-h-[36px] xl:min-h-[40px] 
text-[11px] sm:text-[11px] md:text-[13px] lg:text-[16px] xl:text-[18px] 
rounded-[8px] sm:rounded-[12px] md:rounded-[20px] 
flex justify-start items-center flex-wrap 
${isDark ? 'text-white/80' : 'text-[#471396]'} px-2 sm:px-3 md:px-4 py-[3px] sm:py-1 font-bold italic 
${isDark ? 'bg-[#C9BEFF]/50 border-[#C9BEFF]/20 shadow-md shadow-[#6367FF]/80' : 'bg-[#6367FF]/20 border border-[#6367FF]/20 shadow-md shadow-[#000000]/40'}`

const getTask = (isDark) => `
min-h-[34px] sm:min-h-[36px] md:min-h-[40px] lg:min-h-[44px] xl:min-h-[45px] 
w-[98%] sm:w-[95%] md:w-[92%] lg:w-[90%] 
text-[12px] sm:text-[11px] md:text-[13px] lg:text-[15px] xl:text-[18px] 
rounded-[8px] sm:rounded-[10px] md:rounded-[12px] 
flex justify-start items-center flex-wrap 
 font-medium px-2 sm:px-3 md:px-4 py-1 
${isDark ? 'text-[#ffffff]' : 'text-[#471396]'}
${isDark ? 'border-[#C9BEFF]/80 border-1' : 'border-[#6367FF]/80 border-1'}`

const Page = () => {
 const { isDark, toggleDark, accent } = useTheme()

   //page functionality states
  const [currentPage, setCurrentPage] = useState('roadmap')
  const [loading, setLoading] = useState(false)

  // calling the roadmap data generated by karina in the UI 
  const [roadmapData, setRoadmapData] = useState([])
  const [careerData, setCareerData] = useState(null)

  const router = useRouter()

useEffect(() => {
  const stored = localStorage.getItem("roadmap")
  if (!stored) return

  const parsed = JSON.parse(stored)

  console.log("FULL DATA:", parsed)
  console.log("ROADMAP FIELD:", parsed.roadmap)
  console.log("TYPE:", typeof parsed.roadmap)

  const roadmapArray = parsed.roadmap || []

  setRoadmapData(roadmapArray)
  setCareerData(parsed.careerDestination || null)
}, [])

const fetchRoadmap = async (goal) => {
  try {
    setLoading(true)
    const res = await fetch("/api/generate-roadmap", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ user_input: goal })
    })

    if (!res.ok) {
      throw new Error(`API error: ${res.status}`)
    }

    const data = await res.json()
    console.log("FULL PARSED DATA:", data)

    if (data.error) {
      console.error("API returned error:", data.error)
      return
    }

    let roadmapArray = data.roadmap || []

    if (!Array.isArray(roadmapArray)) {
      console.error("Roadmap is not array:", roadmapArray)
      roadmapArray = []
    }

    setRoadmapData(roadmapArray)
    setCareerData(data.careerDestination || null)

    localStorage.setItem("roadmap", JSON.stringify(data))

  } catch (err) {
    console.error("Error fetching roadmap:", err)
  } finally {
    setLoading(false)
  }
}

  return (
 <div className={`h-screen w-full  flex flex-col md:flex-row `}
 style={{
    minHeight: '100dvh',                          
    paddingTop: 'env(safe-area-inset-top)',        
    paddingBottom: 'env(safe-area-inset-bottom)',  
    paddingLeft: 'env(safe-area-inset-left)',      
    paddingRight: 'env(safe-area-inset-right)',
  }}>

      {/*sidebar - Desktop only */}
     <div className={`hidden md:flex h-full w-[60px] border-r-2 border-[#6367FF] flex-col justify-center items-center gap-3 flex-shrink-0 ${isDark ? 'bg-gradient-to-b from-[#25297D] via-[#171A4F] via-[#101236] to-[#070817]' : 'bg-white '}`}>
        {/* next step logo */}
       <div
          onClick={toggleDark}
            className={`h-[30px] w-[30px] sm:h-[34px] sm:w-[34px] rounded-[10px] flex justify-center items-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer 
            ${isDark ? 'bg-white shadow-md shadow-[#000000]/100' : 'bg-black shadow-md shadow-[#000000]/80'}`}>
            <p className='text-[20px] sm:text-[24px] font-bold text-[#6367FF]'>N</p>
          </div>

          {/*buttons and options */}
          <div className={`h-[85%] w-[90%] border-t-2 border-b-2 flex flex-col justify-center items-center gap-15 lg:gap-12 xl:gap-16 2xl:gap-20
            ${isDark ? 'border-[#6367FF]' : 'border-[#000000]'}`}>

           
           <button onClick={() => setCurrentPage('roadmap')}
            className={`h-[35px] w-[40px]  rounded-[15px] flex justify-center items-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer
             ${isDark ? 'text-[#6367FF]' : 'text-[#6367FF]'}
             ${currentPage === 'roadmap' ? 'text-[#6367FF]' : '' }
             ${currentPage === 'roadmap' ? (isDark ? 'bg-[#6367FF]/20' : 'bg-[#6367FF]/20') : ''}`}>
            <i className="bx bx-book-open text-[30px]" />
          </button>
         


         
            <button onClick={() => setCurrentPage('profile')} 
            className={`h-[35px] w-[40px]  rounded-[15px] flex justify-center items-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer
             ${isDark ? 'text-[#6367FF]' : 'text-[#6367FF]'}
             ${currentPage === 'profile' ? 'text-[#6367FF]' : '' }
             ${currentPage === 'profile' ? (isDark ? 'bg-[#6367FF]/20' : 'bg-[#6367FF]/20') : ''}`}>
               <i className="bx bx-user text-[30px]" />
            </button>
        

           
            <button onClick={() => setCurrentPage('karinachat')} 
             className={`h-[35px] w-[40px]  rounded-[15px] flex justify-center items-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer
             ${isDark ? 'text-[#6367FF]' : 'text-[#6367FF]'}
             ${currentPage === 'karinachat' ? 'text-[#6367FF]' : '' }
             ${currentPage === 'karinachat' ? (isDark ? 'bg-[#6367FF]/20' : 'bg-[#6367FF]/20') : ''}`}>
           <FontAwesomeIcon 
           className='text-[25px]'
           icon={faBandcamp} />
            </button>
            

           
            <button onClick={() => setCurrentPage('history')} 
             className={`h-[35px] w-[40px]  rounded-[15px] flex justify-center items-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer
             ${isDark ? 'text-[#6367FF]' : 'text-[#6367FF]'}
             ${currentPage === 'history' ? 'text-[#6367FF]' : '' }
             ${currentPage === 'history' ? (isDark ? 'bg-[#6367FF]/20' : 'bg-[#6367FF]/20') : ''}`}>
               <i className="bx bx-history text-[30px]" />
            </button>
           

            
           
            <button onClick={() => setCurrentPage('settings')} 
              className={`h-[35px] w-[40px]  rounded-[15px] flex justify-center items-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer
               ${isDark ? 'text-[#6367FF]' : 'text-[#6367FF]'}
               ${currentPage === 'settings' ? 'text-[#6367FF]' : '' }
               ${currentPage === 'settings' ? (isDark ? 'bg-[#6367FF]/20' : 'bg-[#6367FF]/20') : ''}`}>
               <i className="bx bx-cog text-[30px]" />
            </button>
           
          </div>

          {/*feedback and help three dot button */}
          <div className={`h-[40px] w-[40px] flex justify-center items-center rounded-[15px] transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer
           ${isDark ? 'text-[#6367FF]' : 'text-[#6367FF]'}`}>
            <i className="bx bx-dots-horizontal-rounded text-[40px]" />
          </div>
      </div>

      {/* Bottom Navigation Bar - Mobile/Tablet only */}
      <div className={`md:hidden fixed bottom-0 left-0 right-0 h-[70px] bg-white border-t-2 border-[#6367FF] flex justify-around items-center px-4 z-50
       ${isDark ? 'bg-gradient-to-t from-[#25297D] via-[#171A4F] via-[#101236] to-[#070817]' : 'bg-white'}`}>

        <button onClick={() => setCurrentPage('roadmap')}
          className={`flex flex-col items-center justify-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer 
          ${currentPage === 'roadmap' ? 'text-[#6367FF]' : 'text-gray-600'}`}>
          <i className="bx bx-book-open text-[24px]" />
          <span className='text-[10px] mt-1'>Roadmap</span>
        </button>

        <button onClick={() => setCurrentPage('profile')} 
          className={`flex flex-col items-center justify-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer ${currentPage === 'profile' ? 'text-[#6367FF]' : 'text-gray-600'}`}>
          <i className="bx bx-user text-[24px]" />
          <span className='text-[10px] mt-1'>Profile</span>
        </button>

        <button onClick={() => setCurrentPage('karinachat')} 
          className={`flex flex-col items-center justify-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer ${currentPage === 'karinachat' ? 'text-[#6367FF]' : 'text-gray-600'}`}>
          <FontAwesomeIcon className='text-[22px]' icon={faBandcamp} />
          <span className='text-[10px] mt-1'>Karina Chat</span>
        </button>

        <button onClick={() => setCurrentPage('history')} 
          className={`flex flex-col items-center justify-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer ${currentPage === 'history' ? 'text-[#6367FF]' : 'text-gray-600'}`}>
          <i className="bx bx-history text-[24px]" />
          <span className='text-[10px] mt-1'>History</span>
        </button>

        <button onClick={() => setCurrentPage('settings')} 
          className={`flex flex-col items-center justify-center transition-transform duration-300 hover:scale-110 active:scale-95 cursor-pointer ${currentPage === 'settings' ? 'text-[#6367FF]' : 'text-gray-600'}`}>
          <i className="bx bx-cog text-[24px]" />
          <span className='text-[10px] mt-1'>Settings</span>
        </button>
      </div>

      {/* main content area - with padding-bottom for mobile bottom bar */}
      <div className='flex-1  overflow-hidden'>

    {/*roadmap content */}
{currentPage === 'roadmap' && (
  <div className='h-full w-full'>



   {/* roadmap content area */}
 
<div className={`h-[100%] sm:h-[100%] md:h-[100%] lg:h-[100%] xl:h-[100%]
 w-full  flex-col flex justify-start items-center gap-6 sm:gap-8 md:gap-10 pb-[80px]
  overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]`}  


    style={{
        backgroundImage: isDark
          ? `linear-gradient(to right, #25297D, #171A4F, #101236, #070817), 
          radial-gradient(circle, rgba(255,255,255,0.35) 1px, transparent 1px)`
          : `radial-gradient(circle, rgba(99,104,255,0.95) 1px, transparent 1px)`,
        backgroundSize: isDark ? 'cover, 24px 24px' : '24px 24px',
        backgroundBlendMode: isDark ? 'overlay' : 'normal'
    }}>


   {/* floating topbar wrapper — sits above content */}
<div className={`w-full px-3 sm:px-5 py-3 sm:py-4 `}>

  <div className='flex items-center gap-2 sm:gap-3'>

    {/* LEFT — title card floats */}
    <div className={`flex-1 min-w-0
      px-3 sm:px-5 py-2 sm:py-3
      rounded-[14px] sm:rounded-[18px]
    
      flex flex-col justify-center gap-[2px]
      ${isDark ? 'border-l-5 border-r-5 border-[#C9BEFF]' : 'border-l-5 border-r-5 border-[#6367FF]'}
      ${isDark ? 'bg-[#000000]': 'bg-gradient-to-b from-[#E8F9FF] via-[#ffffff] to-[#E8F9FF]'} ${isDark ? 'shadow-md shadow-[#C9BEFF]' : 'shadow-md shadow-[#6367FF]/80'}`}>

      {/* title row */}
      <div className='flex items-center gap-1 sm:gap-2 min-w-0'>
        <span className={`italic font-bold break-words
          text-[15px] sm:text-[20px] md:text-[26px] lg:text-[30px]
          text-[#6367FF]`}>
          <span className='hidden sm:inline'>{careerData?.bestRole || "Career"}</span>
          <span className='sm:hidden'>{careerData?.bestRole ||  "Career"}</span>
        </span>
        <span className={`font-medium truncate
          text-[15px] sm:text-[20px] md:text-[26px] lg:text-[30px]
          ${isDark ? 'text-[#E8E6FF]' : 'text-[#111]'}`}>
          Roadmap
        </span>
        
      </div>

      {/* subtitle */}
      <p className={`italic font-bold break-wordss
        text-[10px] sm:text-[10px] md:text-[12px] 
        ${isDark ? 'text-[#ffffff]/80' : 'text-[#000000]/80'}`}>
        6 phases — from people fundamentals to your first {careerData?.bestRole || "Career"} role
      </p>
    </div>

    {/* RIGHT — action buttons float separately */}
    <div className='flex items-center gap-2 flex-shrink-0'>

      {/* download */}
      <button 
      onClick={() => router.push('/roadmapPDF')}
      className={`h-[40px] sm:h-[44px] md:h-[48px]
        w-[40px] sm:w-auto sm:px-3 md:px-4
        rounded-[12px] sm:rounded-[14px]
        border border-[#6367FF]/25
        flex items-center justify-center gap-2
        
        transition-all duration-200 cursor-pointer
        hover:bg-[#6367FF] hover:border-[#6367FF] hover:text-white hover:scale-108 hover:active:scale-95
        ${isDark ? 'shadow-md shadow-[#C9BEFF]' : 'shadow-md shadow-[#6367FF]'}
        ${isDark
          ? 'bg-[#000000] text-[#ffffff]'
          : 'bg-white text-[#555]'}`}>
        <FontAwesomeIcon className='text-[14px] sm:text-[15px]' icon={faArrowDown} />
        <span className='hidden md:inline text-[12px] font-semibold'>Download</span>
      </button>

      {/* restart */}
      <button 
     onClick={() => router.push('/FreeTrial?restart=true')}
      className={`h-[40px] sm:h-[44px] md:h-[48px]
        w-[40px] sm:w-[44px] md:w-[48px]
        rounded-[12px] sm:rounded-[14px]
        border border-[#6367FF]/25
        flex items-center justify-center
    
        transition-all duration-200 cursor-pointer
        hover:bg-[#6367FF] hover:border-[#6367FF] hover:text-white hover:scale-108 hover:active:scale-95
       ${isDark ? 'shadow-md shadow-[#C9BEFF]' : 'shadow-md shadow-[#6367FF]'}
        ${isDark
          ? 'bg-[#000000] text-[#ffffff]'
          : 'bg-white text-[#555]'}`}>
        <FontAwesomeIcon className='text-[14px] sm:text-[15px]' icon={faRotateLeft} />
      </button>

      {/* ask karina */}
      <button
        onClick={() => setCurrentPage('karina')}
        className={`h-[40px] sm:h-[44px] md:h-[48px]
          px-3 sm:px-4
          rounded-[12px] sm:rounded-[14px]
          bg-[#6367FF] border border-[#6367FF]
          flex items-center gap-2
          text-white font-semibold
          text-[11px] sm:text-[13px]
       
          hover:bg-[#4B4FD9] hover:border-[#4B4FD9] hover:scale-108 hover:active:scale-95
          transition-all duration-200 cursor-pointer
           ${isDark ? 'shadow-md shadow-[#C9BEFF]' : 'shadow-md shadow-[#000000]'}`}>

        <span className='relative flex h-[7px] w-[7px] sm:h-[8px] sm:w-[8px] flex-shrink-0'>
          <span className='animate-ping absolute inline-flex h-full w-full rounded-full bg-[#22c55e] opacity-75'></span>
          <span className='relative inline-flex h-[7px] w-[7px] sm:h-[8px] sm:w-[8px] rounded-full bg-[#22c55e]'></span>
        </span>
        Ask Karina
      </button>

    </div>
  </div>
</div>

  {/* roadmap phases */}
  <div className={`h-[150px] sm:h-[120px] md:h-[140px] lg:h-[150px] w-[90%] 
  sm:w-[90%] md:w-[80%] lg:w-[70%] border border-[#6367FF] rounded-[20px]
   mt-3 sm:mt-4 md:mt-6 lg:mt-8  flex justify-center items-center gap-2 sm:gap-4 md:gap-6 lg:gap-8 px-2 
   ${isDark ? 'border-[#C9BEFF]' : 'border-[#6367FF]'}
   ${isDark ? 'bg-[#C9BEFF]/20' : 'bg-[#6367FF]/20'}`}>

    <FontAwesomeIcon className={`text-[28px] sm:text-[32px] md:text-[36px] lg:text-[40px] 
    
      ${isDark ? 'text-[#C68FE6]' : 'text-[#021A54]'}`} icon={faStar} />

    <div className='h-full w-[80%] flex flex-col justify-center'>

<p className={`italic font-bold text-[14px] sm:text-[15px] 
md:text-[17px] lg:text-[20px] xl:text-[22px] flex justify-start items-center ${isDark ? 'text-[#D4F6FF]' : 'text-[#021A54]'}`}>YOUR CAREER DESTINATION</p>
      <div className='h-auto w-full'>
       <p className={`italic font-bold text-[14px] sm:text-[15px]
        md:text-[17px] lg:text-[18px] xl:text-[20px] flex justify-start items-center ${isDark ? 'text-[#ffffff]' : 'text-[#021A54]'}`}>{careerData?.roles?.join(",")}</p>
        
       <p className={`italic text-[12px] sm:text-[14px]
        md:text-[14px] lg:text-[17px] xl:text-[18px] flex justify-start items-center ${isDark ? 'text-[#ffffff]/80' : 'text-[#021A54]'}`}>At a startup, MNC, or growing tech company</p>
      </div>
    </div>
  </div>





{/* roadmap cards — mapped */}
{Array.isArray(roadmapData) && roadmapData.map((phase, index) => (
  <div key={phase.id} className={getBox(isDark)}>

    {/* heading, number and description */}
    <div className='min-h-[120px] sm:min-h-[120px] md:min-h-[140px] lg:min-h-[150px] w-[95%] flex py-2 sm:py-0  '>

      {/* big number */}
<div className='h-full w-[50px] sm:w-[70px] md:w-[80px] lg:w-[100px]
  flex justify-center items-center flex-shrink-0 '>
 <p className={`text-[35px] sm:text-[55px] md:text-[70px] lg:text-[90px] 
  font-bold leading-none ${isDark ? 'text-[#C9BEFF]' : 'text-[#6367FF]'}`}>
  {String(phase.id).padStart(2, '0')}
</p>
</div>

      {/* heading + pills */}
      <div className='flex-1 flex flex-col justify-center h-auto 
      sm:gap-2 pl-2 sm:pl-3 md:pl-4 min-w-0  '>
        <span className={`text-[20px] sm:text-[20px] md:text-[24px] lg:text-[28px] xl:text-[30px]
          h-[30px] sm:h-[32px] md:h-[36px] lg:h-[50px] w-full  
          ${isDark ? 'text-[#D4F6FF]' : 'text-[#6367FF]'} font-bold leading-tight truncate`}>
          {phase.title}
        </span>
        <p className={getBoxtext(isDark)}>outcome: {phase.outcome || "No description"}</p>
        <p className={getBoxtext(isDark)}>description: {phase.description || "No outcome"}</p>
      </div>
    </div>

    {/* tasks */}
    <div className='w-[95%] flex justify-center items-center flex-col
      gap-2 sm:gap-3 md:gap-4 py-3 sm:py-4 '>
      {(Array.isArray(phase.tasks) ? phase.tasks : []).map((t, i) =>(
        <div key={i} className={getTask(isDark)}>
          {t}
        </div>
      ))}
    </div>

{/* duration + source — stacks on mobile, side by side on tablet+ */}
<div className='w-[95%] sm:w-[92%] md:w-[90%]
  flex flex-col sm:flex-row 
  justify-between items-start sm:items-center
  gap-2  pb-4 '>
  <p className={`${getBoxtext2(isDark)} w-full sm:w-auto sm:min-w-[120px] md:min-w-[140px]`}>
    Duration: {phase.duration || "NA"}
  </p>
  <p className={`${getBoxtext2(isDark)} w-full sm:flex-1`}>
  Source: {Array.isArray(phase.learningSources)
  ? phase.learningSources.join(" · ")
  : phase.learningSources || "NA"}
  </p>
</div>

  </div>
))}
<div className='h-[50px] w-[100%]'></div>
</div>
 </div>)}
        

  {/*profile content */}
{currentPage === 'profile' && (
  <Profilepage isDark={isDark} accent={accent} />
)}
         

       {/*karinachat content */}
        {currentPage === 'karinachat' && (
  <KarinaChat isDark={isDark} accent={accent} />
)}



         {/*history content */}
        {currentPage === 'history' && (
  <History isDark={isDark} accent={accent} />
)}

         {/*settings content */}
               {currentPage === 'settings' && (
  <Settings isDark={isDark} accent={accent} />
)}
      </div>
    </div>
    
  )
}


export default Page

